phrase = "Lambert Academy"
print(phrase.lower())
print(phrase.upper())
print(phrase.isupper())
print(phrase.upper().isupper())
print(len(phrase))
print(phrase[0])
print(phrase.index("A"))
print(phrase.replace("Lambert", "Rofina"))
print("Lov is a powerful tool.")